### Lab 01 - Artificial Intelligence

Use 'Lab1_dataset.csv'

In [1]:
import pandas as pd
import numpy as np
# Read the CSV file into a DataFrame
df = pd.read_csv('Lab1_dataset.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2003,2003,2,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,"""""",Veenker,1Fam,1Story,6.0,8.0,1976,1976,2,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2001,2002,2,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Crawfor,1Fam,2Story,7.0,NaN,1915,1970,3,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,NoRidge,1Fam,2Story,8.0,5.0,-1,2000,3,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,60,RL,69.0,9337,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,6.0,5.0,1997,1997,2,204750
95,96,60,RL,NaN,9765,Pave,NaN,IR2,Lvl,AllPub,Corner,Gilbert,1Fam,2Story,6.0,NaN,1993,1993,2,185000
96,97,20,RL,78.0,10264,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,1Story,7.0,5.0,1999,1999,2,214000
97,98,20,RL,73.0,10921,Pave,NaN,Reg,HLS,AllPub,Inside,Edwards,1Fam,1Story,4.0,5.0,1965,1965,1,94750
98,99,30,RL,85.0,10625,Pave,NaN,Reg,Lvl,AllPub,Corner,Edwards,1Fam,1Story,5.0,5.0,1920,1950,1,83000

#### a) Missing data could be anything in { NA, n/a, “ ”, -1, ...}. Read the data and assign the missing data in the dataframe as NaN. Hint:  df.replace( ..., numpy.nan, inplace=True)

##### Why do we need to replace the missing data with NaN?

Replacing missing data with NaN allows us to easily identify and handle missing values in the dataset. NaN is a standard representation for missing data in pandas, and it provides various functions to handle and analyze missing values effectively. By using NaN, we can perform operations such as filtering, imputation, and analysis without encountering errors or inaccuracies caused by missing data.

##### Why '?' is replaced with NaN?

The '?' symbol is often used in datasets to indicate missing or unknown values. By replacing it with NaN (Not a Number), we can utilize the powerful data manipulation and analysis capabilities of libraries like pandas. 

NaN is a standard way to represent missing data in Python, and it allows us to perform operations such as filtering, aggregation, and statistical analysis without encountering errors that may arise from non-numeric values. 

Additionally, many functions in pandas are designed to handle NaN values appropriately, making it easier to work with incomplete datasets.

##### Why do we need to read the missing data as NaN?
 
Reading missing data as NaN is crucial for accurate data analysis and processing. NaN values allow us to identify and handle missing data effectively. When we read missing data as NaN, we can easily perform operations such as filtering out missing values, calculating statistics while ignoring NaN, and applying imputation techniques to fill in missing values. 

If we were to read missing data as a different placeholder (like '?'), it would require additional steps to identify and handle those values, which can lead to errors and complications in data analysis. 

By using NaN, we can leverage the built-in functionality of pandas and other libraries to manage missing data efficiently, ensuring that our analyses are accurate and reliable.

In [ ]:
#TODO: Read the missing data in dataframe as NaN
df.replace('?', np.nan, inplace=True)
print(df)

    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0    1          60       RL         65.0     8450   Pave   NaN      Reg
1    2          20       RL         80.0     9600   Pave   NaN      Reg
2    3          60       RL         68.0    11250   Pave   NaN      IR1
3    4          70       RL         60.0     9550   Pave   NaN      IR1
4    5          60       RL         84.0    14260   Pave   NaN      IR1
..  ..         ...      ...          ...      ...    ...   ...      ...
94  95          60       RL         69.0     9337   Pave   NaN      IR1
95  96          60       RL          NaN     9765   Pave   NaN      IR2
96  97          20       RL         78.0    10264   Pave   NaN      IR1
97  98          20       RL         73.0    10921   Pave   NaN      Reg
98  99          30       RL         85.0    10625   Pave   NaN      Reg

   LandContour Utilities LotConfig Neighborhood BldgType HouseStyle  \
0          Lvl    AllPub    Inside      CollgCr     1Fam     2Story
1          Lvl    AllPub        ""      Veenker     1Fam     1Story
2          Lvl    AllPub    Inside      CollgCr     1Fam     2Story
3          Lvl    AllPub    Corner      Crawfor     1Fam     2Story
4          Lvl    AllPub       FR2      NoRidge     1Fam     2Story
..         ...       ...       ...          ...      ...        ...
94         Lvl    AllPub    Inside      CollgCr     1Fam     2Story
95         Lvl    AllPub    Corner      Gilbert     1Fam     2Story
96         Lvl    AllPub    Inside      CollgCr     1Fam     1Story
97         HLS    AllPub    Inside      Edwards     1Fam     1Story
98         Lvl    AllPub    Corner      Edwards     1Fam     1Story

    OverallQual  OverallCond  YearBuilt  YearRemodAdd  GarageCars  SalePrice
0           7.0          5.0       2003          2003           2     208500
1           6.0          8.0       1976          1976           2     181500
2           7.0          5.0       2001          2002           2     223500
3           7.0          NaN       1915          1970           3     140000
4           8.0          5.0         -1          2000           3     250000
..          ...          ...        ...           ...         ...        ...
94          6.0          5.0       1997          1997           2     204750
95          6.0          NaN       1993          1993           2     185000
96          7.0          5.0       1999          1999           2     214000
97          4.0          5.0       1965          1965           1      94750
98          5.0          5.0       1920          1950           1      83000

[99 rows x 20 columns]

#### b) Show the summary of the dataframe

In [4]:
#TODO: Show the summary of the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            99 non-null     int64
 1   MSSubClass    99 non-null     int64
 2   MSZoning      99 non-null     str
 3   LotFrontage   85 non-null     float64
 4   LotArea       99 non-null     int64
 5   Street        99 non-null     str
 6   Alley         6 non-null      str
 7   LotShape      99 non-null     str
 8   LandContour   99 non-null     str
 9   Utilities     99 non-null     str
 10  LotConfig     99 non-null     str
 11  Neighborhood  99 non-null     str
 12  BldgType      99 non-null     str
 13  HouseStyle    95 non-null     str
 14  OverallQual   94 non-null     float64
 15  OverallCond   95 non-null     float64
 16  YearBuilt     99 non-null     int64
 17  YearRemodAdd  99 non-null     int64
 18  GarageCars    99 non-null     int64
 19  SalePrice     99 non-null     int64
dtypes: float64(3), int64(7), str(10)
memory usage: 15.6 KB

#### c) Count the number and percentage of rows with missing in the entire dataset

In [16]:
#TODO: Count the number and percent of rows with missing data in entire dataset
total_rows = len(df)
rows_with_missing_data = df.isnull().any(axis=1).sum()
percent_missing = (rows_with_missing_data / total_rows) * 100
print(f'Total rows: {total_rows}')
print(f'Rows with missing data: {rows_with_missing_data}')
print(f'Percent of rows with missing data: {percent_missing:.2f}%')

Total rows: 99
Rows with missing data: 93
Percent of rows with missing data: 93.94%

#### d) Count the number and percentage of missing data in each

In [17]:
#TODO: Count the number and percentage of missing data in each rows
missing_data_per_row = df.isnull().sum(axis=1)
percent_missing_per_row = (missing_data_per_row / df.shape[1]) * 100
missing_data_summary = pd.DataFrame({
    'Missing Data Count': missing_data_per_row,
    'Missing Data Percent': percent_missing_per_row
})
missing_data_summary

    Missing Data Count  Missing Data Percent
0                    1                   5.0
1                    1                   5.0
2                    1                   5.0
3                    2                  10.0
4                    1                   5.0
..                 ...                   ...
94                   1                   5.0
95                   3                  15.0
96                   1                   5.0
97                   1                   5.0
98                   1                   5.0

[99 rows x 2 columns]

#### e) Randomly drop 10% of the rows that have missing data. Hint: use any() andnumpy.random.choice()

In [18]:
#TODO: Randomly drop 10% of the rows that have missing data
rows_with_missing_data_indices = df[df.isnull().any(axis=1)].index
num_rows_to_drop = int(0.1 * len(rows_with_missing_data_indices))
rows_to_drop = np.random.choice(rows_with_missing_data_indices, size=num_rows_to_drop, replace=False)
df_dropped = df.drop(index=rows_to_drop)
df_dropped

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2003,2003,2,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,"""""",Veenker,1Fam,1Story,6.0,8.0,1976,1976,2,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.0,2001,2002,2,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Crawfor,1Fam,2Story,7.0,NaN,1915,1970,3,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,NoRidge,1Fam,2Story,8.0,5.0,-1,2000,3,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,60,RL,69.0,9337,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,6.0,5.0,1997,1997,2,204750
95,96,60,RL,NaN,9765,Pave,NaN,IR2,Lvl,AllPub,Corner,Gilbert,1Fam,2Story,6.0,NaN,1993,1993,2,185000
96,97,20,RL,78.0,10264,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,1Story,7.0,5.0,1999,1999,2,214000
97,98,20,RL,73.0,10921,Pave,NaN,Reg,HLS,AllPub,Inside,Edwards,1Fam,1Story,4.0,5.0,1965,1965,1,94750
98,99,30,RL,85.0,10625,Pave,NaN,Reg,Lvl,AllPub,Corner,Edwards,1Fam,1Story,5.0,5.0,1920,1950,1,83000

#### f) Fill in the missing data with median (if the column data type is numeric) or mode (if the column data type is not numeric)

In [19]:
#TODO: Fill the missing data with mean (if numeric) or mode (if non-numeric)
for column in df.columns:
    if df[column].dtype in [np.float64, np.int64]:  # Check if the column is numeric
        mean_value = df[column].mean()
        df[column].fillna(mean_value, inplace=True)
    else:  # Non-numeric column
        mode_value = df[column].mode()[0]
        df[column].fillna(mode_value, inplace=True)
df

/tmp/ipykernel_76825/650133932.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(mean_value, inplace=True)
/tmp/ipykernel_76825/650133932.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(mode_value, inplace=True)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
0,1,60,RL,65.000000,8450,Pave,Grvl,Reg,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.000000,2003,2003,2,208500
1,2,20,RL,80.000000,9600,Pave,Grvl,Reg,Lvl,AllPub,"""""",Veenker,1Fam,1Story,6.0,8.000000,1976,1976,2,181500
2,3,60,RL,68.000000,11250,Pave,Grvl,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,7.0,5.000000,2001,2002,2,223500
3,4,70,RL,60.000000,9550,Pave,Grvl,IR1,Lvl,AllPub,Corner,Crawfor,1Fam,2Story,7.0,5.473684,1915,1970,3,140000
4,5,60,RL,84.000000,14260,Pave,Grvl,IR1,Lvl,AllPub,FR2,NoRidge,1Fam,2Story,8.0,5.000000,-1,2000,3,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,60,RL,69.000000,9337,Pave,Grvl,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,2Story,6.0,5.000000,1997,1997,2,204750
95,96,60,RL,71.341176,9765,Pave,Grvl,IR2,Lvl,AllPub,Corner,Gilbert,1Fam,2Story,6.0,5.473684,1993,1993,2,185000
96,97,20,RL,78.000000,10264,Pave,Grvl,IR1,Lvl,AllPub,Inside,CollgCr,1Fam,1Story,7.0,5.000000,1999,1999,2,214000
97,98,20,RL,73.000000,10921,Pave,Grvl,Reg,HLS,AllPub,Inside,Edwards,1Fam,1Story,4.0,5.000000,1965,1965,1,94750
98,99,30,RL,85.000000,10625,Pave,Grvl,Reg,Lvl,AllPub,Corner,Edwards,1Fam,1Story,5.0,5.000000,1920,1950,1,83000

#### g) Show the summary of the updated dataframe

In [21]:
#TODO: Show summary of updated dataframe
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            99 non-null     int64
 1   MSSubClass    99 non-null     int64
 2   MSZoning      99 non-null     object
 3   LotFrontage   99 non-null     float64
 4   LotArea       99 non-null     int64
 5   Street        99 non-null     object
 6   Alley         99 non-null     object
 7   LotShape      99 non-null     object
 8   LandContour   99 non-null     object
 9   Utilities     99 non-null     object
 10  LotConfig     99 non-null     object
 11  Neighborhood  99 non-null     object
 12  BldgType      99 non-null     object
 13  HouseStyle    99 non-null     object
 14  OverallQual   99 non-null     float64
 15  OverallCond   99 non-null     float64
 16  YearBuilt     99 non-null     int64
 17  YearRemodAdd  99 non-null     int64
 18  GarageCars    99 non-null     int64
 19  SalePrice     99 non-null     int64
dtypes: float64(3), int64(7), object(10)
memory usage: 15.6+ KB
None

#### h) Extract the row with max SalePrice and the row with min SalePrice

In [23]:
#TODO: Extract row with max SalePrice
max_sale_price_row = df[df['SalePrice'] == df['SalePrice'].max()]
max_sale_price_row

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
58,59,60,RL,66.0,13682,Pave,Grvl,IR2,HLS,AllPub,CulDSac,StoneBr,1Fam,2Story,10.0,5.0,2006,2006,3,438780

In [25]:
#TODO:Extract row with min SalePrice
min_sale_price_row = df[df['SalePrice'] == df['SalePrice'].min()]
min_sale_price_row

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,SalePrice
30,31,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,Inside,IDOTRR,1Fam,2Story,4.0,4.0,1920,1950,1,40000

#### i) Insert a new column called Overall, which is the average of OverallQual and OverallCond.

In [29]:
#TODO: Create new column name Overall (average of OverallQual and OverallCond)
df['Overall'] = (df['OverallQual'] + df['OverallCond']) /2
df[['OverallQual', 'OverallCond', 'Overall']]

    OverallQual  OverallCond   Overall
0           7.0     5.000000  6.000000
1           6.0     8.000000  7.000000
2           7.0     5.000000  6.000000
3           7.0     5.473684  6.236842
4           8.0     5.000000  6.500000
..          ...          ...       ...
94          6.0     5.000000  5.500000
95          6.0     5.473684  5.736842
96          7.0     5.000000  6.000000
97          4.0     5.000000  4.500000
98          5.0     5.000000  5.000000

[99 rows x 3 columns]

#### j) Update the dataframe with SalePrice used as index and ID becomes a new column

In [32]:
#TODO: Update dataframe with SalePrice used as index
df.set_index('SalePrice', inplace=True)
# ID becomes a new column
df.reset_index(inplace=True)
df

,SalePrice,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,LotConfig,Neighborhood,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,GarageCars,Overall
0,208500,1,60,RL,65.000000,8450,Pave,Grvl,Reg,Lvl,...,Inside,CollgCr,1Fam,2Story,7.0,5.000000,2003,2003,2,6.000000
1,181500,2,20,RL,80.000000,9600,Pave,Grvl,Reg,Lvl,...,"""""",Veenker,1Fam,1Story,6.0,8.000000,1976,1976,2,7.000000
2,223500,3,60,RL,68.000000,11250,Pave,Grvl,IR1,Lvl,...,Inside,CollgCr,1Fam,2Story,7.0,5.000000,2001,2002,2,6.000000
3,140000,4,70,RL,60.000000,9550,Pave,Grvl,IR1,Lvl,...,Corner,Crawfor,1Fam,2Story,7.0,5.473684,1915,1970,3,6.236842
4,250000,5,60,RL,84.000000,14260,Pave,Grvl,IR1,Lvl,...,FR2,NoRidge,1Fam,2Story,8.0,5.000000,-1,2000,3,6.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,204750,95,60,RL,69.000000,9337,Pave,Grvl,IR1,Lvl,...,Inside,CollgCr,1Fam,2Story,6.0,5.000000,1997,1997,2,5.500000
95,185000,96,60,RL,71.341176,9765,Pave,Grvl,IR2,Lvl,...,Corner,Gilbert,1Fam,2Story,6.0,5.473684,1993,1993,2,5.736842
96,214000,97,20,RL,78.000000,10264,Pave,Grvl,IR1,Lvl,...,Inside,CollgCr,1Fam,1Story,7.0,5.000000,1999,1999,2,6.000000
97,94750,98,20,RL,73.000000,10921,Pave,Grvl,Reg,HLS,...,Inside,Edwards,1Fam,1Story,4.0,5.000000,1965,1965,1,4.500000
98,83000,99,30,RL,85.000000,10625,Pave,Grvl,Reg,Lvl,...,Corner,Edwards,1Fam,1Story,5.0,5.000000,1920,1950,1,5.000000