In [2]:
#import libraries
import pandas as pd

#load dataset
df = pd.read_csv('mtcars.csv')
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## 1. Group by cyl and display the first 20 lines after groupby

In [3]:
df.groupby('cyl').head(20)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

## 2. Group by cyl on 'mpg' and display the first 20 lines after groupby

In [3]:
df.groupby('cyl')['mpg'].head(20)

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

## 3. Group by cyl, select column 'mpg', then aggregate on mean

In [ ]:
df.groupby('cyl')['mpg'].mean()

cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

## 4. Group by cyl, select columns [‘mpg’, ‘hp’] then aggregate on mean

In [5]:
df.groupby('cyl')[['mpg', 'hp']].mean()

           mpg          hp
cyl
4    26.663636   82.636364
6    19.742857  122.285714
8    15.100000  209.214286

## 5.Group by [cyl, am], select 2 columns [‘mpg’, ‘hp’] then aggregate on mean

In [6]:
df.groupby(['cyl', 'am'])[['mpg', 'hp']].mean()

              mpg          hp
cyl am
4   0   22.900000   84.666667
    1   28.075000   81.875000
6   0   19.125000  115.250000
    1   20.566667  131.666667
8   0   15.050000  194.166667
    1   15.400000  299.500000

## 6. Group by [cyl], select 2 columns [‘mpg’, ‘hp’] then aggregate on mean, std

In [7]:
df.groupby('cyl')[['mpg', 'hp']].agg(['mean', 'std'])

           mpg                    hp
          mean       std        mean        std
cyl
4    26.663636  4.509828   82.636364  20.934530
6    19.742857  1.453567  122.285714  24.260491
8    15.100000  2.560048  209.214286  50.976886

## 7.Group by [cyl, am], get 2 columns [‘mpg’, ‘hp’] then aggregate on mean, std

In [8]:
df.groupby(['cyl', 'am'])[['mpg', 'hp']].agg(['mean', 'std'])

              mpg                    hp
             mean       std        mean        std
cyl am
4   0   22.900000  1.452584   84.666667  19.655364
    1   28.075000  4.483860   81.875000  22.655416
6   0   19.125000  1.631717  115.250000   9.178780
    1   20.566667  0.750555  131.666667  37.527767
8   0   15.050000  2.774396  194.166667  33.359838
    1   15.400000  0.565685  299.500000  50.204581

## 8.Count the number of Toyota and Mercedes grouped by am.

In [9]:
df[df['model'].str.contains('Toyota|Merc')].groupby('am')['model'].count()

am
0    8
1    1
Name: model, dtype: int64

## 9.Count the number of Toyota and Mercedes with more than 4 cylinders grouped by am

In [10]:
df_filtered = df[df['model'].str.contains('Toyota|Merc')]
df_filtered = df_filtered[df_filtered['cyl'] > 4]
df_filtered.groupby('am').size()

am
0    5
dtype: int64

## 10. Count the number of cars per cylinder.

In [11]:
df.groupby('cyl').size()

cyl
4    11
6     7
8    14
dtype: int64