In [2]:
#import library

import pandas as pd

df = pd.read_csv('mtcars.csv')
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## 1. Group by cyl, then apply aggregate funcƟons (mean) on ‘mpg’

In [2]:
pd.pivot_table(df, values='mpg', index='cyl', aggfunc='mean')

           mpg
cyl
4    26.663636
6    19.742857
8    15.100000

## 2. Group by cyl, then apply aggregate funcƟons (mean) on [‘mpg’, ‘hp’]

In [3]:
pd.pivot_table(df, values=['mpg','hp'], index='cyl', aggfunc='mean')

             hp        mpg
cyl
4     82.636364  26.663636
6    122.285714  19.742857
8    209.214286  15.100000

## 3. Group by [cyl, am], then apply aggregate funcƟons (mean) on [‘mpg’, ‘hp’]

In [4]:
pd.pivot_table(df, values=['mpg','hp'], index=['cyl','am'], aggfunc='mean')

                hp        mpg
cyl am
4   0    84.666667  22.900000
    1    81.875000  28.075000
6   0   115.250000  19.125000
    1   131.666667  20.566667
8   0   194.166667  15.050000
    1   299.500000  15.400000

## 4.Group by [cyl], then apply aggregate functions (mean, std) on [‘mpg’, ‘hp’]

In [5]:
pd.pivot_table(df, values=['mpg','hp'], index='cyl', aggfunc=['mean','std'])

           mean                   std
             hp        mpg         hp       mpg
cyl
4     82.636364  26.663636  20.934530  4.509828
6    122.285714  19.742857  24.260491  1.453567
8    209.214286  15.100000  50.976886  2.560048

## 5. Group by [cyl, am], then apply aggregate functions (mean, std) on [‘mpg’, ‘hp’]

In [6]:
pd.pivot_table(df, values=['mpg','hp'], index=['cyl','am'], aggfunc=['mean','std'])

              mean                   std
                hp        mpg         hp       mpg
cyl am
4   0    84.666667  22.900000  19.655364  1.452584
    1    81.875000  28.075000  22.655416  4.483860
6   0   115.250000  19.125000   9.178780  1.631717
    1   131.666667  20.566667  37.527767  0.750555
8   0   194.166667  15.050000  33.359838  2.774396
    1   299.500000  15.400000  50.204581  0.565685

## 6. Group by [cyl, am], then apply aggregate functions (mean, median, std) on ‘mpg’ and  then apply aggregate functions(min, max) on ‘hp’.Also, usefill_value = 0, margins = True, margins_name = “Total”.

In [8]:
pd.pivot_table(
    df,
    values='mpg',
    index=['cyl', 'am'],
    columns='gear',
    aggfunc=['mean','std', 'median'],
    fill_value=0,
    margins=True,
    margins_name='Total'
)

               mean                                    std            \
gear              3          4      5      Total         3         4
cyl   am
4     0   21.500000  23.600000   0.00  22.900000  0.000000  1.131371
      1    0.000000  28.033333  28.20  28.075000  0.000000  5.118854
6     0   19.750000  18.500000   0.00  19.125000  2.333452  0.989949
      1    0.000000  21.000000  19.70  20.566667  0.000000  0.000000
8     0   15.050000   0.000000   0.00  15.050000  2.774396  0.000000
      1    0.000000   0.000000  15.40  15.400000  0.000000  0.000000
Total     16.106667  24.533333  21.38  20.090625  3.371618  5.276764

                             median
gear             5     Total      3      4     5  Total
cyl   am
4     0   0.000000  1.452584  21.50  23.60   0.0  22.80
      1   3.111270  4.483860   0.00  28.85  28.2  28.85
6     0   0.000000  1.631717  19.75  18.50   0.0  18.65
      1   0.000000  0.750555   0.00  21.00  19.7  21.00
8     0   0.000000  2.774396  15.20   0.00   0.0  15.20
      1   0.565685  0.565685   0.00   0.00  15.4  15.40
Total     6.658979  6.026948  15.50  22.80  19.7  19.20

In [9]:
pd.pivot_table(
    df,
    values='hp',
    index=['cyl', 'am'],
    columns='gear',
    aggfunc=['min','max'],
    fill_value=0,
    margins=True,
    margins_name='Total'
)

          min                  max
gear        3    4    5 Total    3    4    5 Total
cyl   am
4     0    97   62    0    62   97   95    0    97
      1     0   52   91    52    0  109  113   113
6     0   105  123    0   105  110  123    0   123
      1     0  110  175   110    0  110  175   175
8     0   150    0    0   150  245    0    0   245
      1     0    0  264   264    0    0  335   335
Total      97   52   91    52  245  123  335   335

## 7.Group by [cyl], set pivot table column as [gear],  then apply aggregate funcƟons (mean, std) on [‘mpg’, ‘hp’]. Also, usefill_value = 0, margins = True, margins_name = “Total”.

In [5]:
pd.pivot_table(
    df,
    values=['mpg','hp'],
    index='cyl',
    columns='gear',
    aggfunc=['mean','std'],
    fill_value=0,
    margins=True,
    margins_name='Total'
)

             mean                                                         \
               hp                                  mpg
gear            3      4      5       Total          3          4      5
cyl
4       97.000000   76.0  102.0   82.636364  21.500000  26.925000  28.20
6      107.500000  116.5  175.0  122.285714  19.750000  19.750000  19.70
8      194.166667    0.0  299.5  209.214286  15.050000   0.000000  15.40
Total  176.133333   89.5  195.6  146.687500  16.106667  24.533333  21.38

                        std                                              \
                         hp                                         mpg
gear       Total          3          4           5      Total         3
cyl
4      26.663636   0.000000  20.113961   15.556349  20.934530  0.000000
6      19.742857   3.535534   7.505553    0.000000  24.260491  2.333452
8      15.100000  33.359838   0.000000   50.204581  50.976886  2.774396
Total  20.090625  47.689272  25.893137  102.833847  68.562868  3.371618



gear          4         5     Total
cyl
4      4.807360  3.111270  4.509828
6      1.552417  0.000000  1.453567
8      0.000000  0.565685  2.560048
Total  5.276764  6.658979  6.026948

## 8. Group by [cyl, am], set pivot table columns as [gear, carb], then apply aggregate funcƟons (mean, std)on [‘mpg’, ‘hp’]. Also, usefill_value = 0, margins = True, margins_name = “Total”.

In [10]:
pd.pivot_table(
    df,
    values=['mpg','hp'],
    index=['cyl','am'],
    columns=['gear','carb'],
    aggfunc=['mean','std'],
    fill_value=0,
    margins=True,
    margins_name='Total'
)

           mean                                                               \
             hp
gear          3                          4                   5
carb          1      2      3      4     1     2      4      2      4      6
cyl   am
4     0    97.0    0.0    0.0    0.0   0.0  78.5    0.0    0.0    0.0    0.0
      1     0.0    0.0    0.0    0.0  72.5  80.5    0.0  102.0    0.0    0.0
6     0   107.5    0.0    0.0    0.0   0.0   0.0  123.0    0.0    0.0    0.0
      1     0.0    0.0    0.0    0.0   0.0   0.0  110.0    0.0    0.0  175.0
8     0     0.0  162.5  180.0  228.0   0.0   0.0    0.0    0.0    0.0    0.0
      1     0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0  264.0    0.0
Total     104.0  162.5  180.0  228.0  72.5  79.5  116.5  102.0  264.0  175.0

          ...        std                                                   \
          ...         hp       mpg
gear      ...      Total         3                                      4
carb      ...                    1         2         3         4        1
cyl   am  ...
4     0   ...  19.655364  0.000000  0.000000  0.000000  0.000000  0.00000
      1   ...  22.655416  0.000000  0.000000  0.000000  0.000000  5.06162
6     0   ...   9.178780  2.333452  0.000000  0.000000  0.000000  0.00000
      1   ...  37.527767  0.000000  0.000000  0.000000  0.000000  0.00000
8     0   ...  33.359838  0.000000  2.092048  1.053565  2.089737  0.00000
      1   ...        NaN       NaN       NaN       NaN       NaN      NaN
Total     ...  68.562868  1.934770  2.092048  1.053565  2.089737  5.06162



gear                                5     Total
carb             2         4        2
cyl   am
4     0   1.131371  0.000000  0.00000  1.452584
      1   6.363961  0.000000  3.11127  4.483860
6     0   0.000000  0.989949  0.00000  1.631717
      1   0.000000  0.000000  0.00000  0.750555
8     0   0.000000  0.000000  0.00000  2.774396
      1        NaN       NaN      NaN       NaN
Total     3.961060  1.552417  3.11127  6.026948

[7 rows x 42 columns]

## 9. Group by [cyl, am], set pivot table columns as [gear, carb], then apply aggregate functions (lambda funcƟon: sqrt(sum(x*x))) on [‘mpg’, ‘hp’]. Also, usefill_value = 0, margins = True, margins_name = “Total”.

In [11]:
from math import sqrt

pd.pivot_table(
    df,
    values=['mpg','hp'],
    index=['cyl','am'],
    columns=['gear','carb'],
    aggfunc=lambda x: sqrt(sum(x*x)),
    fill_value=0,
    margins=True,
    margins_name='Total'
)

                  hp                                                 \
gear               3                                              4
carb               1          2           3           4           1
cyl   am
4     0    97.000000    0.00000    0.000000    0.000000    0.000000
      1     0.000000    0.00000    0.000000    0.000000  146.921748
6     0   152.069063    0.00000    0.000000    0.000000    0.000000
      1     0.000000    0.00000    0.000000    0.000000    0.000000
8     0     0.000000  325.96012  311.769145  511.077294    0.000000
      1     0.000000    0.00000    0.000000    0.000000    0.000000
Total     180.371838  325.96012  311.769145  511.077294  146.921748

                                                            ...        mpg  \
gear                                       5                ...          3
carb               2           4           2      4      6  ...          3
cyl   am                                                    ...
4     0   113.441615    0.000000    0.000000    0.0    0.0  ...   0.000000
      1   120.768373    0.000000  145.086181    0.0    0.0  ...   0.000000
6     0     0.000000  173.948268    0.000000    0.0    0.0  ...   0.000000
      1     0.000000  155.563492    0.000000    0.0  175.0  ...   0.000000
8     0     0.000000    0.000000    0.000000    0.0    0.0  ...  28.271717
      1     0.000000    0.000000    0.000000  264.0    0.0  ...   0.000000
Total     165.692486  233.362379  145.086181  264.0  175.0  ...  28.271717

                                                                          \
gear                         4                             5
carb              4          1          2          4       2     4     6
cyl   am
4     0    0.000000   0.000000  33.394610   0.000000   0.000   0.0   0.0
      1    0.000000  58.856605  37.176875   0.000000  40.002   0.0   0.0
6     0    0.000000   0.000000   0.000000  26.181673   0.000   0.0   0.0
      1    0.000000   0.000000   0.000000  29.698485   0.000   0.0  19.7
8     0   28.527005   0.000000   0.000000   0.000000   0.000   0.0   0.0
      1    0.000000   0.000000   0.000000   0.000000   0.000  15.8   0.0
Total     28.527005  58.856605  49.973193  39.591413  40.002  15.8  19.7


gear                 Total
carb         8
cyl   am
4     0    0.0   39.717125
      1    0.0   80.289352
6     0    0.0   38.354270
      1    0.0   35.638322
8     0    0.0   52.940533
      1   15.0   21.786234
Total     15.0  118.500253

[7 rows x 24 columns]

## 10. Use df.apply()and a lambda funcƟon, insert a new column called “Code” that uses the FIRST 3 letters of the “model” and 2 leƩers of the code of the COUNTRY: {code: countrycode}. all LOWERCASE.

In [16]:
def get_country_code(model):
    country_dict = {
        'jp': ['toyota','honda','datsun','mazda'],
        'eu': ['merc','ferrari','volvo','porsche','maserati','lotus'],
    }
    name = model.lower()
    for code, brands in country_dict.items():
        if any(b in name for b in brands):
            return code
    return 'us'

df['country_code'] = df.apply(
    lambda x: f"{x['model'][:3].lower()}:{get_country_code(x['model'])}",
    axis=1
)
df[['model','country_code']].head(10)

               model country_code
0          Mazda RX4       maz:jp
1      Mazda RX4 Wag       maz:jp
2         Datsun 710       dat:jp
3     Hornet 4 Drive       hor:us
4  Hornet Sportabout       hor:us
5            Valiant       val:us
6         Duster 360       dus:us
7          Merc 240D       mer:eu
8           Merc 230       mer:eu
9           Merc 280       mer:eu