# Lab 02: LINEAR REGRESSION

In [2]:
#libraries
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import pandas as pd

df = pd.read_csv('Housing.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

### 1. Use only area to predict house price

In [2]:
# Use only area to predict house price
df1 = df[['area', 'price']]

# normalize the data using MinMaxScaler
scaler = MinMaxScaler()
df1_scaled = scaler.fit_transform(df1)

# split the data into training and testing sets
X_df1 = df1_scaled[:, 0].reshape(-1, 1)  # area
y_df1 = df1_scaled[:, 1]  # price
X_train_df1, X_test_df1, y_train_df1, y_test_df1 = train_test_split(
    X_df1, y_df1, test_size=0.2, random_state=42)

# Write Linear Equation
model = LinearRegression()
model.fit(X_train_df1, y_train_df1)

#Predict the price of a house based on its area
predicted_prices_scaled = model.predict(X_test_df1)
# dataframe to store actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price (scaled)': y_test_df1,
    'Predicted Price (scaled)': predicted_prices_scaled
})

#Compute MSE
y_pred_df1 = model.predict(X_test_df1)
mse_df1 = mean_squared_error(y_test_df1, y_pred_df1)
print(f'Mean Squared Error: {mse_df1}')

#Compute coefficient of determination R-squared score
r_squared_df1 = model.score(X_test_df1, y_test_df1)
print(f'R-squared score: {r_squared_df1}')

results_df

Mean Squared Error: 0.02755035778765904
R-squared score: 0.27287851871974633

     Actual Price (scaled)  Predicted Price (scaled)
0                 0.200000                  0.283468
1                 0.424242                  0.305584
2                 0.169697                  0.214909
3                 0.406061                  0.250295
4                 0.090909                  0.211961
..                     ...                       ...
104               0.636364                  0.287154
105               0.175152                  0.321434
106               0.533333                  0.287154
107               0.484848                  0.287154
108               0.327273                  0.290840

[109 rows x 2 columns]

### 2. Use only area, bedrooms

In [3]:
# Use only area to predict house price
df2 = df[['area','bedrooms', 'price']]

# normalize the data using MinMaxScaler
scaler = MinMaxScaler()
df2_scaled = scaler.fit_transform(df2)

# split the data into training and testing sets
X_df2 = df2_scaled[:, :2]  # area and bedrooms
y_df2 = df2_scaled[:, 2]  # price
X_train_df2, X_test_df2, y_train_df2, y_test_df2 = train_test_split(X_df2, y_df2, test_size=0.2, random_state=42)

# Write Linear Equation
model = LinearRegression()
model.fit(X_train_df2, y_train_df2)

#Predict the price of a house based on its area
predicted_prices_scaled = model.predict(X_test_df2)
# dataframe to store actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price (scaled)': y_test_df2,
    'Predicted Price (scaled)': predicted_prices_scaled
})

#Compute MSE
y_pred_df2 = model.predict(X_test_df2)
mse_df2 = mean_squared_error(y_test_df2, y_pred_df2)
print(f'Mean Squared Error: {mse_df2}')

#Compute coefficient of determination R-squared score
r_squared_df2 = model.score(X_test_df2, y_test_df2)
print(f'R-squared score: {r_squared_df2}')

results_df

Mean Squared Error: 0.024588569145810743
R-squared score: 0.3510473817558716

     Actual Price (scaled)  Predicted Price (scaled)
0                 0.200000                  0.343830
1                 0.424242                  0.303817
2                 0.169697                  0.160685
3                 0.406061                  0.253268
4                 0.090909                  0.218221
..                     ...                       ...
104               0.636364                  0.347200
105               0.175152                  0.378540
106               0.533333                  0.347200
107               0.484848                  0.286968
108               0.327273                  0.290338

[109 rows x 2 columns]

### 3. Use only area, bedrooms, bathrooms

In [4]:
# Use only area to predict house price
df3 = df[['area','bedrooms','bathrooms', 'price']]

# normalize the data using MinMaxScaler
scaler = MinMaxScaler()
df3_scaled = scaler.fit_transform(df3)

# split the data into training and testing sets
X_df3 = df3_scaled[:, :3]  # area, bedrooms, and bathrooms
y_df3 = df3_scaled[:, 3]  # price
X_train_df3, X_test_df3, y_train_df3, y_test_df3 = train_test_split(X_df3, y_df3, test_size=0.2, random_state=42)

# Write Linear Equation
model = LinearRegression()
model.fit(X_train_df3, y_train_df3)

#Predict the price of a house based on its area
predicted_prices_scaled = model.predict(X_test_df3)
# dataframe to store actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price (scaled)': y_test_df3,
    'Predicted Price (scaled)': predicted_prices_scaled
})

#Compute MSE
y_pred_df3 = model.predict(X_test_df3)
mse_df3 = mean_squared_error(y_test_df3, y_pred_df3)
print(f'Mean Squared Error: {mse_df3}')

#Compute coefficient of determination R-squared score
r_squared_df3 = model.score(X_test_df3, y_test_df3)
print(f'R-squared score: {r_squared_df3}')

results_df

Mean Squared Error: 0.020614609766001796
R-squared score: 0.45592991188724397

     Actual Price (scaled)  Predicted Price (scaled)
0                 0.200000                  0.401140
1                 0.424242                  0.387900
2                 0.169697                  0.159990
3                 0.406061                  0.219890
4                 0.090909                  0.188783
..                     ...                       ...
104               0.636364                  0.280987
105               0.175152                  0.308803
106               0.533333                  0.404131
107               0.484848                  0.372945
108               0.327273                  0.375936

[109 rows x 2 columns]

### 4. Use only area, bedrooms, bathrooms, stories

In [5]:
# Use only area to predict house price
df4 = df[['area','bedrooms','bathrooms', 'stories', 'price']]

# normalize the data using MinMaxScaler
scaler = MinMaxScaler()
df4_scaled = scaler.fit_transform(df4)

# split the data into training and testing sets
X_df4 = df4_scaled[:, :4]  # area, bedrooms, bathrooms, and stories
y_df4 = df4_scaled[:, 4]  # price
X_train_df4, X_test_df4, y_train_df4, y_test_df4 = train_test_split(X_df4, y_df4, test_size=0.2, random_state=42)

# Write Linear Equation
model = LinearRegression()
model.fit(X_train_df4, y_train_df4)

#Predict the price of a house based on its area
predicted_prices_scaled = model.predict(X_test_df4)
# dataframe to store actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price (scaled)': y_test_df4,
    'Predicted Price (scaled)': predicted_prices_scaled
})

#Compute MSE
y_pred_df4 = model.predict(X_test_df4)
mse_df4 = mean_squared_error(y_test_df4, y_pred_df4)
print(f'Mean Squared Error: {mse_df4}')

#Compute coefficient of determination R-squared score
r_squared_df4 = model.score(X_test_df4, y_test_df4)
print(f'R-squared score: {r_squared_df4}')

results_df

Mean Squared Error: 0.018423505121883694
R-squared score: 0.5137585349037065

     Actual Price (scaled)  Predicted Price (scaled)
0                 0.200000                  0.383340
1                 0.424242                  0.428239
2                 0.169697                  0.146064
3                 0.406061                  0.232089
4                 0.090909                  0.158771
..                     ...                       ...
104               0.636364                  0.277431
105               0.175152                  0.305533
106               0.533333                  0.470147
107               0.484848                  0.371237
108               0.327273                  0.332367

[109 rows x 2 columns]

### 5. Use only area, bedrooms, bathrooms, stories, parking

In [7]:
# Use only area to predict house price
df5 = df[['area','bedrooms','bathrooms', 'stories', 'parking','price']]

# normalize the data using MinMaxScaler
scaler = MinMaxScaler()
df5_scaled = scaler.fit_transform(df5)

# split the data into training and testing sets
X_df5 = df5_scaled[:, :5]  # area, bedrooms, bathrooms, stories, and parking
y_df5 = df5_scaled[:, 5]  # price
X_train_df5, X_test_df5, y_train_df5, y_test_df5 = train_test_split(X_df5, y_df5, test_size=0.2, random_state=42)

# Write Linear Equation
model = LinearRegression()
model.fit(X_train_df5, y_train_df5)

#Predict the price of a house based on its area
predicted_prices_scaled = model.predict(X_test_df5)
# dataframe to store actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price (scaled)': y_test_df5,
    'Predicted Price (scaled)': predicted_prices_scaled
})

#Compute MSE
y_pred_df5 = model.predict(X_test_df5)
mse_df5 = mean_squared_error(y_test_df5, y_pred_df5)
print(f'Mean Squared Error: {mse_df5}')

#Compute coefficient of determination R-squared score
r_squared_df5 = model.score(X_test_df5, y_test_df5)
print(f'R-squared score: {r_squared_df5}')

results_df

Mean Squared Error: 0.017186496098089366
R-squared score: 0.5464062355495862

     Actual Price (scaled)  Predicted Price (scaled)
0                 0.200000                  0.383431
1                 0.424242                  0.400012
2                 0.169697                  0.132740
3                 0.406061                  0.214373
4                 0.090909                  0.143696
..                     ...                       ...
104               0.636364                  0.312679
105               0.175152                  0.308314
106               0.533333                  0.471837
107               0.484848                  0.373010
108               0.327273                  0.362053

[109 rows x 2 columns]

### 6. Use only area, bedrooms, bathrooms, stories, parking, airconditioning (yes->, no->0)

In [ ]:
# Use only area to predict house price
df6 = df[['area','bedrooms','bathrooms', 'stories', 'parking', 'airconditioning','price']]
#turn airconditioning into binary variable
df6['airconditioning'] = df6['airconditioning'].apply(lambda x: 1 if x == 'yes' else 0)

# normalize the data using MinMaxScaler
scaler = MinMaxScaler()
df6_scaled = scaler.fit_transform(df6)

# split the data into training and testing sets
X_df6 = df6_scaled[:, :6]  # area, bedrooms, bathrooms, stories, parking, and airconditioning
y_df6 = df6_scaled[:, 6]  # price
X_train_df6, X_test_df6, y_train_df6, y_test_df6 = train_test_split(X_df6, y_df6, test_size=0.2, random_state=42)

# Write Linear Equation
model = LinearRegression()
model.fit(X_train_df6, y_train_df6)

#Predict the price of a house based on its area
predicted_prices_scaled = model.predict(X_test_df6)
# dataframe to store actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price (scaled)': y_test_df6,
    'Predicted Price (scaled)': predicted_prices_scaled
})

#Compute MSE
y_pred_df6 = model.predict(X_test_df6)
mse_df6 = mean_squared_error(y_test_df6, y_pred_df6)
print(f'Mean Squared Error: {mse_df6}')

#Compute coefficient of determination R-squared score
r_squared_df6 = model.score(X_test_df6, y_test_df6)
print(f'R-squared score: {r_squared_df6}')

results_df

Mean Squared Error: 0.015586746378668016
R-squared score: 0.5886275524061089

     Actual Price (scaled)  Predicted Price (scaled)
0                 0.200000                  0.349310
1                 0.424242                  0.435942
2                 0.169697                  0.126443
3                 0.406061                  0.269918
4                 0.090909                  0.136274
..                     ...                       ...
104               0.636364                  0.278227
105               0.175152                  0.276554
106               0.533333                  0.491248
107               0.484848                  0.416833
108               0.327273                  0.335553

[109 rows x 2 columns]

### Summarize MSE, R2 metric of 6 cases in the a Table

In [ ]:
# Summarize MSE, R2 metric of 6 cases in the a Table
summary_df = pd.DataFrame({
    'Features': ['area', 'area, bedrooms', 'area, bedrooms, bathrooms', 
                    'area, bedrooms, bathrooms, stories', 'area, bedrooms, bathrooms, stories, parking', 
                    'area, bedrooms, bathrooms, stories, parking, airconditioning'],
    'MSE': [mse_df1, mse_df2, mse_df3, mse_df4, mse_df5, mse_df6],
    'R-squared': [r_squared_df1, r_squared_df2, r_squared_df3, r_squared_df4, r_squared_df5, r_squared_df6]
})
summary_df

                                            Features       MSE  R-squared
0                                               area  0.027550   0.272879
1                                     area, bedrooms  0.024589   0.351047
2                          area, bedrooms, bathrooms  0.020615   0.455930
3                 area, bedrooms, bathrooms, stories  0.018424   0.513759
4        area, bedrooms, bathrooms, stories, parking  0.017186   0.546406
5  area, bedrooms, bathrooms, stories, parking, a...  0.015587   0.588628