In [13]:
#Import library
import numpy as np
import pandas as pd

#Read database

df = pd.read_csv('Customers.csv')
df

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size
0,Uriah,Bridges,Male,19,15000,39,Healthcare,1,4
1,Paula,Small,Female,21,35000,81,Engineer,3,3
2,Edward,Buck,Female,20,86000,6,Engineer,1,1
3,Michael,Riordan,Male,23,59000,77,Lawyer,0,2
4,Jasmine,Onque,Female,31,38000,40,Entertainment,2,6
...,...,...,...,...,...,...,...,...,...
195,Danika,Fleming,Female,35,46000,79,Executive,1,3
196,Jocelyn,Kline,Female,45,78000,28,Artist,0,2
197,Cesar,Higgins,Male,32,4000,74,Artist,1,5
198,Gabriel,Dodson,Male,32,81000,18,Executive,1,2
199,Raphael,Sandoval,Male,30,33000,83,Artist,4,2

1. Insert a new column called Initials that combine the first letter of FirstName and LastName (use .map() a Lambda function). For example: Joseph Martins -> JM

In [14]:
df['Initials'] = df[['FirstName','LastName']].apply(lambda x: x['FirstName'][0] + x['LastName'][0], axis=1)
df['Initials'].head()

0    UB
1    PS
2    EB
3    MR
4    JO
Name: Initials, dtype: object

2. Find the number of duplicates and remove the duplicated, and only keep the first entry

In [15]:
#Num of Duplicate
num_duplicates = df.duplicated().sum()
print('Number of duplicated rows: ', num_duplicates)

df[df.duplicated()]

Number of duplicated rows:  6

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size,Initials
64,Sonny,Horne,Female,49,88000,52,Artist,1,2,SH
90,Geovanni,Pugh,Female,45,67000,53,Doctor,0,2,GP
127,Samara,Mcbride,Female,49,79000,59,Artist,0,2,SM
142,Samara,Mcbride,Female,49,79000,59,Artist,0,2,SM
178,Brayden,Malone,Male,42,79000,20,Homemaker,9,3,BM
190,Brayden,Malone,Male,42,79000,20,Homemaker,9,3,BM

In [17]:
#Drop Duplicated
df.drop_duplicates(keep='first')

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size,Initials
0,Uriah,Bridges,Male,19,15000,39,Healthcare,1,4,UB
1,Paula,Small,Female,21,35000,81,Engineer,3,3,PS
2,Edward,Buck,Female,20,86000,6,Engineer,1,1,EB
3,Michael,Riordan,Male,23,59000,77,Lawyer,0,2,MR
4,Jasmine,Onque,Female,31,38000,40,Entertainment,2,6,JO
...,...,...,...,...,...,...,...,...,...,...
195,Danika,Fleming,Female,35,46000,79,Executive,1,3,DF
196,Jocelyn,Kline,Female,45,78000,28,Artist,0,2,JK
197,Cesar,Higgins,Male,32,4000,74,Artist,1,5,CH
198,Gabriel,Dodson,Male,32,81000,18,Executive,1,2,GD
199,Raphael,Sandoval,Male,30,33000,83,Artist,4,2,RS

3. Find the number of profession

In [20]:
print('Number of Profession: ', df['Profession'].nunique())
df['Profession'].value_counts()

Number of Profession:  9

Profession
Artist           75
Healthcare       30
Engineer         20
Lawyer           17
Executive        16
Doctor           13
Entertainment    12
Homemaker         9
Marketing         6
Name: count, dtype: int64

4. Find the average income

In [27]:
print("Average of Annual Income: ", df['Annual Income ($)'].mean(), "$")

Average of Annual Income:  54770.0 $

5. Find the median income

In [26]:
print("Median of Annual Income: ", df['Annual Income ($)'].median(), "$")

Median of Annual Income:  57500.0 $

6. Extract info [FirstName, LastName, Gender, Age, Annual Income, Spending Score, Profession] of Male Engineers above 20 years old with income over 60000 $

In [78]:
df.loc[(df.Age>20) & 
       (df.Gender == 'Male') & 
       (df.Profession == 'Engineer') & 
       (df['Annual Income ($)'] > 60000), 
       ['FirstName', 'LastName', 'Gender', 'Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Profession']]

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession
8,Jac,McKinzie,Male,64,97000,3,Engineer
126,Khalil,Mendez,Male,43,89000,35,Engineer
144,Marilyn,Linares,Male,25,71000,12,Engineer

7. Extract info [FirstName, LastName, Gender, Age, Annual Income, Spending Score, Profession] of Female Artist between 20-40 years old with income below 40000 $

In [79]:
df.loc[(df.Age.between(20,40,inclusive='both')) & 
       (df.Gender == 'Female') & 
       (df.Profession == 'Artist') & 
       (df['Annual Income ($)'] < 40000), 
       ['FirstName', 'LastName', 'Gender', 'Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Profession']]

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession
28,Charity,Miranda,Female,40,18000,31,Artist
29,Axel,Howe,Female,23,20000,87,Artist
38,Willow,Stuart,Female,36,9000,26,Artist
43,Esteban,Gilbert,Female,31,33000,61,Artist
94,Jocelyn,Bradford,Female,32,24000,42,Artist
139,Maliki,Moumanil,Female,35,15000,72,Artist
175,Helena,Davenport,Female,30,28000,86,Artist

8. Extract those whose first name is Jac (use Series.str.contains())

In [80]:
df.loc[df.FirstName.str.contains('Jac', case=False, na=False)]

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size,Initials
8,Jac,McKinzie,Male,64,97000,3,Engineer,0,3,JM
23,Jac,Moyer,Male,31,71000,73,Artist,5,2,JM
42,Jac,Shepherd,Male,48,22000,36,Artist,14,3,JS

9.
    Extract those whose spending score is above 70
    
    Extract males whose spending score is above 70
    
    Extract females whose spending score is above 70

In [81]:
#All Gender Spending Score Above 70
df.loc[df['Spending Score (1-100)'] > 70]

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size,Initials
1,Paula,Small,Female,21,35000,81,Engineer,3,3,PS
3,Michael,Riordan,Male,23,59000,77,Lawyer,0,2,MR
5,Maruk,Fraval,Female,22,58000,76,Artist,0,2,MF
7,Sharlene,Terry,Female,23,84000,94,Healthcare,1,3,ST
9,Joseph,Martins,Female,30,98000,72,Artist,1,4,JM
11,Dheepa,Nguyen,Female,35,93000,99,Healthcare,4,4,DN
13,Xana,Potts,Female,24,91000,77,Lawyer,1,1,XP
15,Kaylah,Moon,Male,22,51000,79,Healthcare,1,2,KM
19,Hector,Dalton,Female,35,62000,98,Artist,0,1,HD
21,Angela,Molina,Male,25,4000,73,Healthcare,3,4,AM
23,Jac,Moyer,Male,31,71000,73,Artist,5,2,JM
25,Jaydon,Blackburn,Male,29,52000,82,Artist,1,3,JB
29,Axel,Howe,Female,23,20000,87,Artist,5,4,AH
31,Cory,Robinson,Female,21,34000,73,Doctor,1,2,CR
33,Alisa,James,Male,18,62000,92,Homemaker,9,7,AJ
35,Aliana,Nolan,Female,21,95000,81,Healthcare,3,4,AN
37,James,Duke,Female,30,62000,73,Healthcare,1,5,JD
39,Clayton,Walker,Female,20,69000,75,Artist,8,2,CW
41,Valentin,Reilly,Male,24,85000,92,Healthcare,0,2,VR
123,Charlie,Atkinson,Male,39,6000,91,Healthcare,1,3,CA
125,Harper,Ramos,Female,31,46000,77,Marketing,1,2,HR
129,Damien,Howe,Male,38,64000,75,Entertainment,8,5,DH
131,Mildred,Gentry,Male,39,26000,75,Lawyer,0,2,MG
133,Joanne,Handschiegl,Female,31,45000,71,Artist,5,1,JH
135,Jean,Crimmings,Female,29,92000,88,Executive,5,5,JC
137,Susan,Lundy,Male,32,85000,73,Artist,3,4,SL
139,Maliki,Moumanil,Female,35,15000,72,Artist,4,4,MM
141,Quinn,Rarrick,Male,32,66000,93,Artist,0,5,QR
143,Adrienne J,Homberger,Female,32,85000,87,Lawyer,1,2,AH
145,Timothy,Sullivan,Male,28,26000,97,Marketing,8,5,TS
147,Anna,Von Massenbach,Female,32,38000,74,Lawyer,1,1,AV
149,Angela,Erilus,Male,34,90000,90,Artist,6,3,AE
151,Clinton,Owad,Male,39,41000,88,Engineer,0,1,CO
153,Davion,Sanchez,Female,38,92000,76,Artist,2,2,DS
155,Augustus,Drake,Female,27,10000,89,Marketing,8,4,AD
157,Orlando,Armstrong,Female,30,87000,78,Artist,3,4,OA
159,Jaqueline,Terrell,Female,30,86000,73,Artist,3,3,JT
161,Selena,Greer,Female,29,50000,83,Healthcare,1,5,SG
163,Dominik,Mullen,Female,31,58000,93,Healthcare,1,5,DM
165,Andre,Guzman,Female,36,54000,75,Artist,5,3,AG
167,Maribel,Morrison,Female,33,83000,95,Artist,0,5,MM
171,Derick,Rocha,Male,28,4000,75,Executive,0,2,DR
173,Marely,Dixon,Male,36,99000,92,Artist,5,2,MD
175,Helena,Davenport,Female,30,28000,86,Artist,3,4,HD
179,Clarissa,Winters,Male,35,42000,90,Engineer,8,1,CW
181,Ally,Zhang,Female,32,61000,86,Entertainment,7,5,AZ
183,Kayley,Myers,Female,29,66000,88,Artist,4,4,KM
185,Edward,Mann,Male,30,72000,97,Artist,6,2,EM
189,Ruben,Lewis,Female,36,95000,85,Artist,4,2,RL
193,Noel,Ramirez,Female,38,45000,91,Artist,10,4,NR
195,Danika,Fleming,Female,35,46000,79,Executive,1,3,DF
197,Cesar,Higgins,Male,32,4000,74,Artist,1,5,CH
199,Raphael,Sandoval,Male,30,33000,83,Artist,4,2,RS

In [82]:
#All Male Spending Score Above 70
male_ss70 = df.loc[(df['Spending Score (1-100)'] > 70) &
   (df.Gender == 'Male')]
male_ss70

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size,Initials
3,Michael,Riordan,Male,23,59000,77,Lawyer,0,2,MR
15,Kaylah,Moon,Male,22,51000,79,Healthcare,1,2,KM
21,Angela,Molina,Male,25,4000,73,Healthcare,3,4,AM
23,Jac,Moyer,Male,31,71000,73,Artist,5,2,JM
25,Jaydon,Blackburn,Male,29,52000,82,Artist,1,3,JB
33,Alisa,James,Male,18,62000,92,Homemaker,9,7,AJ
41,Valentin,Reilly,Male,24,85000,92,Healthcare,0,2,VR
123,Charlie,Atkinson,Male,39,6000,91,Healthcare,1,3,CA
129,Damien,Howe,Male,38,64000,75,Entertainment,8,5,DH
131,Mildred,Gentry,Male,39,26000,75,Lawyer,0,2,MG
137,Susan,Lundy,Male,32,85000,73,Artist,3,4,SL
141,Quinn,Rarrick,Male,32,66000,93,Artist,0,5,QR
145,Timothy,Sullivan,Male,28,26000,97,Marketing,8,5,TS
149,Angela,Erilus,Male,34,90000,90,Artist,6,3,AE
151,Clinton,Owad,Male,39,41000,88,Engineer,0,1,CO
171,Derick,Rocha,Male,28,4000,75,Executive,0,2,DR
173,Marely,Dixon,Male,36,99000,92,Artist,5,2,MD
179,Clarissa,Winters,Male,35,42000,90,Engineer,8,1,CW
185,Edward,Mann,Male,30,72000,97,Artist,6,2,EM
197,Cesar,Higgins,Male,32,4000,74,Artist,1,5,CH
199,Raphael,Sandoval,Male,30,33000,83,Artist,4,2,RS

In [83]:
#All Female Spending Score Above 70
female_ss70 = df.loc[(df['Spending Score (1-100)'] > 70) &
   (df.Gender == 'Female')]
female_ss70

,FirstName,LastName,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size,Initials
1,Paula,Small,Female,21,35000,81,Engineer,3,3,PS
5,Maruk,Fraval,Female,22,58000,76,Artist,0,2,MF
7,Sharlene,Terry,Female,23,84000,94,Healthcare,1,3,ST
9,Joseph,Martins,Female,30,98000,72,Artist,1,4,JM
11,Dheepa,Nguyen,Female,35,93000,99,Healthcare,4,4,DN
13,Xana,Potts,Female,24,91000,77,Lawyer,1,1,XP
19,Hector,Dalton,Female,35,62000,98,Artist,0,1,HD
29,Axel,Howe,Female,23,20000,87,Artist,5,4,AH
31,Cory,Robinson,Female,21,34000,73,Doctor,1,2,CR
35,Aliana,Nolan,Female,21,95000,81,Healthcare,3,4,AN
37,James,Duke,Female,30,62000,73,Healthcare,1,5,JD
39,Clayton,Walker,Female,20,69000,75,Artist,8,2,CW
125,Harper,Ramos,Female,31,46000,77,Marketing,1,2,HR
133,Joanne,Handschiegl,Female,31,45000,71,Artist,5,1,JH
135,Jean,Crimmings,Female,29,92000,88,Executive,5,5,JC
139,Maliki,Moumanil,Female,35,15000,72,Artist,4,4,MM
143,Adrienne J,Homberger,Female,32,85000,87,Lawyer,1,2,AH
147,Anna,Von Massenbach,Female,32,38000,74,Lawyer,1,1,AV
153,Davion,Sanchez,Female,38,92000,76,Artist,2,2,DS
155,Augustus,Drake,Female,27,10000,89,Marketing,8,4,AD
157,Orlando,Armstrong,Female,30,87000,78,Artist,3,4,OA
159,Jaqueline,Terrell,Female,30,86000,73,Artist,3,3,JT
161,Selena,Greer,Female,29,50000,83,Healthcare,1,5,SG
163,Dominik,Mullen,Female,31,58000,93,Healthcare,1,5,DM
165,Andre,Guzman,Female,36,54000,75,Artist,5,3,AG
167,Maribel,Morrison,Female,33,83000,95,Artist,0,5,MM
175,Helena,Davenport,Female,30,28000,86,Artist,3,4,HD
181,Ally,Zhang,Female,32,61000,86,Entertainment,7,5,AZ
183,Kayley,Myers,Female,29,66000,88,Artist,4,4,KM
189,Ruben,Lewis,Female,36,95000,85,Artist,4,2,RL
193,Noel,Ramirez,Female,38,45000,91,Artist,10,4,NR
195,Danika,Fleming,Female,35,46000,79,Executive,1,3,DF

10. Find the percentage of Male with spending score above 70 vs percentage of Female with spending score above 70

In [84]:
#Total Number of each Gender Entire DataFrame
total_male = df.loc[df.Gender == 'Male'].shape[0]
total_female = df.loc[df.Gender == 'Female'].shape[0]

#Percentage of each Gender with Spending Score Above 70
male_percent = (male_ss70.shape[0] / total_male) * 100
female_percent = (female_ss70.shape[0] / total_female) * 100

print(f"Percentage of Male with Spending Score > 70: {male_percent:.2f}%")
print(f"Percentage of Female with Spending Score > 70: {female_percent:.2f}%")

Percentage of Male with Spending Score > 70: 24.14%
Percentage of Female with Spending Score > 70: 28.32%