## 1.Write Python code to create the 3 dfs above. Hint: df = pd.DataFrame(data) where data is a dicƟonary with keys = column names, values = list  of data in the corresponding columns

In [24]:
#import libraries
import pandas as pd

#Create 3 dataframes
#Data for df_player
df_player = {
    'Player':    ['Milner', 'Countinho', 'Kane', 'Son', 'Rooney', 'Baines', 'Hazard'],
    'Team':      ['Liverpool', 'Liverpool', 'Tottenham', 'Tottenham', 'Everton', 'Everton', 'Chelsea'],
    'Goals':     [2, 5, 10, 6, 4, 1, 7],
    'Assists':   [12, 4, 4, 10, 7, 1, 8]
}
df_player = pd.DataFrame(df_player)
df_player

      Player       Team  Goals  Assists
0     Milner  Liverpool      2       12
1  Countinho  Liverpool      5        4
2       Kane  Tottenham     10        4
3        Son  Tottenham      6       10
4     Rooney    Everton      4        7
5     Baines    Everton      1        1
6     Hazard    Chelsea      7        8

In [25]:
#Data for df_teams
df_teams = {
    'Team':        ['Liverpool', 'Tottenham', 'Everton', 'Chelsea'],
    'Home_City':     ['Liverpool', 'London', 'Liverpool', 'London'],
    'Num_Fans':    [0.2, 2.3, 0.1, 5.1]
}
df_teams = pd.DataFrame(df_teams)
df_teams

        Team  Home_City  Num_Fans
0  Liverpool  Liverpool       0.2
1  Tottenham     London       2.3
2    Everton  Liverpool       0.1
3    Chelsea     London       5.1

In [26]:
# Data for df_city
df_city = {
    'City':       ['London', 'Liverpool'],
    'Population': [9.0, 0.5],
}
df_city = pd.DataFrame(df_city)
df_city

        City  Population
0     London         9.0
1  Liverpool         0.5

## 2. Merge the 3 dfs (called df_merged) using only 1 line of code

In [27]:

df_merged = pd.merge(pd.merge(df_player, df_teams, on='Team'), df_city, left_on='Home_City', right_on='City')
df_merged

,Player,Team,Goals,Assists,Home_City,Num_Fans,City,Population
0,Milner,Liverpool,2,12,Liverpool,0.2,Liverpool,0.5
1,Countinho,Liverpool,5,4,Liverpool,0.2,Liverpool,0.5
2,Kane,Tottenham,10,4,London,2.3,London,9.0
3,Son,Tottenham,6,10,London,2.3,London,9.0
4,Rooney,Everton,4,7,Liverpool,0.1,Liverpool,0.5
5,Baines,Everton,1,1,Liverpool,0.1,Liverpool,0.5
6,Hazard,Chelsea,7,8,London,5.1,London,9.0

## 3. Join the 3 dfs (called df_joined). You might need to set_index() before you could join them

In [28]:
df_joined = df_player.set_index('Team').join(df_teams.set_index('Team')).join(df_city.set_index('City'))
df_joined

              Player  Goals  Assists  Home_City  Num_Fans  Population
Team
Liverpool     Milner      2       12  Liverpool       0.2         0.5
Liverpool  Countinho      5        4  Liverpool       0.2         0.5
Tottenham       Kane     10        4     London       2.3         NaN
Tottenham        Son      6       10     London       2.3         NaN
Everton       Rooney      4        7  Liverpool       0.1         NaN
Everton       Baines      1        1  Liverpool       0.1         NaN
Chelsea       Hazard      7        8     London       5.1         NaN

## 4. Remove Home_City from df_merged

In [29]:
df_merged = df_merged.drop(columns='Home_City')
df_merged

      Player       Team  Goals  Assists  Num_Fans       City  Population
0     Milner  Liverpool      2       12       0.2  Liverpool         0.5
1  Countinho  Liverpool      5        4       0.2  Liverpool         0.5
2       Kane  Tottenham     10        4       2.3     London         9.0
3        Son  Tottenham      6       10       2.3     London         9.0
4     Rooney    Everton      4        7       0.1  Liverpool         0.5
5     Baines    Everton      1        1       0.1  Liverpool         0.5
6     Hazard    Chelsea      7        8       5.1     London         9.0

## 5.Find the player with the highest goals and then print out his statistics

In [30]:
df_merged.loc[df_merged['Goals'].idxmax()]

Player             Kane
Team          Tottenham
Goals                10
Assists               4
Num_Fans            2.3
City             London
Population          9.0
Name: 2, dtype: object

## 6.Find the total number of goals of players from the sameteams. Print out just the teams and the total goals.

In [31]:
df_merged.groupby('Team')['Goals'].sum().reset_index()

        Team  Goals
0    Chelsea      7
1    Everton      5
2  Liverpool      7
3  Tottenham     16

## 7. Use filter, print out players from London who scored more than 2 goals.

In [32]:
df_merged[(df_merged['City'] == 'London') & (df_merged['Goals'] > 2)]

   Player       Team  Goals  Assists  Num_Fans    City  Population
2    Kane  Tottenham     10        4       2.3  London         9.0
3     Son  Tottenham      6       10       2.3  London         9.0
6  Hazard    Chelsea      7        8       5.1  London         9.0

## 8. Print out the TOP player (by total goals and assists) from each team. Only show his name, team, total goals and assists.

In [33]:
df_merged['Total'] = df_merged['Goals'] + df_merged['Assists']
top_per_team = df_merged.loc[df_merged.groupby('Team')['Total'].idxmax(), ['Player', 'Team', 'Total']]
top_per_team

   Player       Team  Total
6  Hazard    Chelsea     15
4  Rooney    Everton     11
0  Milner  Liverpool     14
3     Son  Tottenham     16

## 9. Insert a new column called “Star” that gives a “*” to players whose total goals and assists are greater than 12. Otherwise, just leave it empty.

In [34]:
df_merged['Star'] = df_merged['Total'].apply(lambda x: '*' if x > 12 else '')
df_merged

,Player,Team,Goals,Assists,Num_Fans,City,Population,Total,Star
0,Milner,Liverpool,2,12,0.2,Liverpool,0.5,14,*
1,Countinho,Liverpool,5,4,0.2,Liverpool,0.5,9,
2,Kane,Tottenham,10,4,2.3,London,9.0,14,*
3,Son,Tottenham,6,10,2.3,London,9.0,16,*
4,Rooney,Everton,4,7,0.1,Liverpool,0.5,11,
5,Baines,Everton,1,1,0.1,Liverpool,0.5,2,
6,Hazard,Chelsea,7,8,5.1,London,9.0,15,*

## 10.Create a dictionary D {“Player”: Goal} using df. iterrows()

In [36]:
D = {row['Player']: row['Goals'] for index, row in df_merged.iterrows()}
D

{'Milner': 2,
 'Countinho': 5,
 'Kane': 10,
 'Son': 6,
 'Rooney': 4,
 'Baines': 1,
 'Hazard': 7}